name: Welcome and Please Star This Repository <3
on:
  pull_request_target:
    types: [opened, closed]
  issues:
    types: [opened]
permissions:
  contents: read  # Set permissions as read-only by default at the top level
jobs:
  run:
    permissions:
      issues: write  # for wow-actions/welcome to comment on issues
      pull-requests: write  # wow-actions/welcome to comment on PR
    # Do not run on bots and maintainers
    if: ${{ !contains(fromJson('["dependabot[bot]", "dependabot-preview[bot]", "allcontributors[bot]"]'), github.actor) 
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1.3.1
        with:
          FIRST_ISSUE_REACTIONS: '+1, hooray, rocket, heart

          FIRST_ISSUE: |
            ðŸ‘‹ @{{ author }}
            
             Welcome to the SlimPlanet Community! â¤ï¸
             
             We are thrilled to have you with us.

             Thanks for opening your first issue here! Be sure to follow the issue template!
          
          FIRST_PR_REACTIONS: '+1, hooray, rocket, heart'
          
          FIRST_PR: |
            ðŸ‘‹ @{{ author }}

            Welcome to the SlimPlanet Community! â¤ï¸
            
            Thanks for opening this pull request! Please follow the [contributing guidelines](https://github.com/SlimPlanet/SlimFaas/blob/main/CONTRIBUTING.md).

          FIRST_PR_MERGED: |
            ðŸŽ‰ @{{ author }}

            Welcome to the SlimPlanet Community! â¤ï¸
            
            Congrats on merging your first pull request! 

            Kudos and please keep going, we need you ðŸŒ

          STAR_MESSAGE: |

            ðŸ“¢ If you like SlimFaas, please â­ star â­ our repo to support it!
            
            ðŸ™ It really helps the project to gain momentum and credibility.
                      
